import test from 'node:test';import assert from 'node:assert/strict';
import {freshBattle,planState,forecast,loadBattle,saveBattle,movePath,canFire} from '../dist/narai/battle.js';
import {TEXT,translate} from '../dist/narai/i18n.js';
test('forecast is deterministic and never mutates committed state',()=>{const s=freshBattle(),before=JSON.stringify(s),orders=[{type:'move',x:5,z:9},{type:'guard'}];const a=forecast(s,orders);assert.deepEqual(a,forecast(s,orders));assert.equal(JSON.stringify(s),before);assert.equal(a.planned.escort.z,9);assert.equal(a.next.escort.z,10);});
test('invalid crew, commands, collisions and repeated attacks are rejected',()=>{const s=freshBattle();assert.throws(()=>planState(s,[],{helm:2,guns:2,repair:1}),/crewInvalid/);assert.throws(()=>planState(s,[{type:'guard'},{type:'anchor'},{type:'parley'}]),/commandsFull/);assert.equal(movePath(s,{x:0,z:12}),null);assert.equal(movePath(s,{x:6,z:13}),null);assert.throws(()=>planState(s,[{type:'anchor'},{type:'move',x:5,z:11}]),/anchored/);s.enemies[0].x=2;s.enemies[0].z=12;assert.ok(canFire(s.escort,s.enemies[0]));assert.throws(()=>planState(s,[{type:'fire',target:'raider1',aim:'hull'},{type:'fire',target:'raider1',aim:'hull'}]),/alreadyFired/);});
test('rigging, repairs, ammunition and parley obey their resource rules',()=>{const s=freshBattle();s.enemies[0].x=2;s.enemies[0].z=12;s.escort.hp=65;const p=planState(s,[{type:'fire',target:'raider1',aim:'rigging'},{type:'repair'}]);assert.equal(p.ammo,7);assert.equal(p.timber,2);assert.equal(p.escort.hp,83);assert.equal(p.enemies[0].disabled,2);assert.throws(()=>planState({...s,parley:false},[{type:'parley'}]),/parleyUsed/);assert.throws(()=>planState(s,[{type:'fire',target:'raider1',aim:'hull'}],{helm:2,guns:0,repair:1}),/needGuns/);});
test('passive play fails but a well-timed parley can secure passage',()=>{for(const strategic of[false,true]){let s=freshBattle();while(s.status==='playing'&&s.round<15)s=forecast(s,strategic&&s.round===3?[{type:'parley'}]:[]).next;assert.equal(s.status,strategic?'won':'lost');assert.throws(()=>forecast(s,[]),/finished/);}});
test('save restores the committed round and excludes uncommitted plans',()=>{const db={getItem(){return this.value},setItem(k,v){this.value=v}},s=forecast(freshBattle(),[{type:'anchor'}]).next;saveBattle(db,s);assert.deepEqual(loadBattle(db),s);const invalid={...s,crew:{helm:99,guns:1,repair:1}};saveBattle(db,invalid);assert.deepEqual(loadBattle(db),freshBattle());assert.equal(saveBattle({setItem(){throw Error()}},s),false);});
test('all prototype messages have English and Thai text with matching placeholders',()=>{for(const[key,pair]of Object.entries(TEXT)){assert.equal(pair.length,2,key);assert.ok(typeof pair[0]==='string'&&typeof pair[1]==='string',key);if(key!=='noError')assert.ok(pair[0].length&&pair[1].length,key);assert.deepEqual((pair[0].match(/\{\w+\}/g)||[]).sort(),(pair[1].match(/\{\w+\}/g)||[]).sort(),key);}assert.equal(translate('th','round',{n:3}),'รอบที่ 3');});

test("optional event parameters translate safely",()=>{assert.equal(translate("th",undefined),"");});
