import test from 'node:test';import assert from 'node:assert/strict';
import {BUILDINGS,describePlace,townBuildings,townBlocks,cardinalInput,cardinalStep} from '../dist/places.js';
import {roomRoute,walkable} from '../dist/interiors.js';
import {newGame,loadGame,saveGame} from '../dist/state.js';
import {advanceExpedition} from '../dist/expedition.js';
test('all six destinations and caravan gate are reachable without crossing buildings',()=>{const spec=describePlace('alexandria-town'),blocks=townBlocks();for(const b of townBuildings('alexandria')){const path=roomRoute(spec.spawn,{x:b.x,z:b.z+b.d/2+1.15},blocks,spec.bounds);assert.ok(path?.length,b.name);for(const p of path)assert.ok(walkable(p.x,p.z,blocks,spec.bounds));}assert.ok(roomRoute(spec.spawn,{x:0,z:-21},blocks,spec.bounds));assert.equal(BUILDINGS.length,6);});
test('keyboard and click movement stay cardinal and preserve facing',()=>{const input=cardinalInput(new Set(['w','d']));assert.deepEqual(input,{x:1,z:0});let p={x:.13,z:.13};for(let i=0;i<50;i++){const n=cardinalStep(p,{x:2,z:-2},.2);assert.ok(n.x===p.x||n.z===p.z,'never diagonal');p=n;}assert.ok(Math.hypot(p.x-2,p.z+2)<.02);assert.equal(p.facing,'down');assert.deepEqual(cardinalInput(new Set(['w','a','s'])),{x:0,z:1});});
test('interior doors return to the right town and town bounds are much larger',()=>{for(const city of['lisbon','london','alexandria'])for(const b of townBuildings(city))assert.equal(describePlace(b.target).parent,city+'-town');assert.ok(describePlace('lisbon-town').bounds.x>describePlace('lisbon').bounds.x*3);assert.equal(describePlace('holyland').parent,'alexandria-town');});
test('Holy Land expedition requires first story, correct locations and awards once',()=>{const s=newGame(),base=s.gold;assert.equal(advanceExpedition(s,'accept','lisbon-archive').ok,false);s.story.phase='complete';s.story.choice='crew';s.story.companion='mara';assert.equal(advanceExpedition(s,'accept','lisbon-archive').ok,true);assert.equal(advanceExpedition(s,'record','holyland').ok,false);assert.equal(advanceExpedition(s,'read','london-archive').ok,false);assert.equal(advanceExpedition(s,'read','alexandria-archive').ok,true);assert.equal(advanceExpedition(s,'record','holyland').ok,true);const db={getItem(){return this.value},setItem(k,v){this.value=v}};saveGame(db,s);const restored=loadGame(db);assert.equal(restored.expedition.phase,'recorded');assert.equal(advanceExpedition(restored,'finish','alexandria-archive').ok,true);assert.equal(restored.gold,base+450);assert.equal(advanceExpedition(restored,'finish','alexandria-archive').ok,false);assert.equal(restored.gold,base+450);});
